name: Deploy Angular Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - 'angular.json'
      - 'tsconfig.json'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout code
        uses: actions/checkout@v4

      - name: â¬‡ï¸ Setup Node.js with Cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json  # AsegÃºrate de que existe

      - name: ğŸ“¦ Install dependencies
        run: npm install --prefer-offline
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: ğŸ—ï¸ Build for Production
        run: npm run build -- --configuration=production
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: ğŸ“¤ Copy build to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          source: "dist/sidi-frontend/browser/*"
          target: "/home/ubuntu/build"

      - name: ğŸ§© Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          script: |
            # Copiar
            cp -r ./build/dist/sidi-frontend/browser/* /var/www/html/sidi/

            rm -r build
            
            echo "âœ… Frontend pegado en $TARGET_DIR y carpeta build eliminada"

      - name: âœ… Success
        run: echo "ğŸ‰ Frontend desplegado con Ã©xito"
